trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y unzip
    curl -fsSL https://releases.hashicorp.com/terraform/1.13.4/terraform_1.13.4_linux_amd64.zip -o terraform.zip
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    terraform --version
  displayName: Install Terraform

- script: |
    cd parent_module
    terraform init
    terraform validate
  displayName: Terraform Init and Validate

- script: |
    cd parent_module
    terraform plan
  displayName: Terraform Plan
